CREATE TABLE login_attempts (
    id BIGINT(19) NOT NULL AUTO_INCREMENT,
    user_id BIGINT(19) NOT NULL DEFAULT '0',
    ip VARCHAR(255) NOT NULL DEFAULT '0',
    timestamp BIGINT(19) NOT NULL DEFAULT '0',
    PRIMARY KEY (id) USING BTREE,

    INDEX FK_USERS_LOGIN_ATTEMPTS (user_id) USING BTREE,

    CONSTRAINT FK_USERS_LOGIN_ATTEMPTS
        FOREIGN KEY (user_id)
        REFERENCES users (id)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);
