CREATE TABLE products (
    id BIGINT(19) NOT NULL AUTO_INCREMENT,
    title VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,
    price FLOAT NULL DEFAULT '0',
    cost FLOAT NULL DEFAULT '0',
    stock FLOAT NULL DEFAULT '0',
    ready_to_sell TINYINT(1) NOT NULL DEFAULT '0',
    image_url VARCHAR(255) NULL DEFAULT 'default.png',
    created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    user_id BIGINT(19) NULL DEFAULT NULL,
    store_id BIGINT(19) NULL DEFAULT NULL,
    category_id BIGINT(19) NULL DEFAULT NULL,
    PRIMARY KEY (id) USING BTREE,

    INDEX FK_USERS_PRODUCTS (user_id) USING BTREE,
    INDEX FK_STORES_PRODUCTS (store_id) USING BTREE,
    INDEX FK_CATEGORIES_PRODUCTS (category_id) USING BTREE,

    CONSTRAINT FK_USERS_PRODUCTS 
    FOREIGN KEY (user_id) 
    REFERENCES users (id) 
    ON UPDATE NO ACTION 
    ON DELETE CASCADE,

    CONSTRAINT FK_STORES_PRODUCTS 
    FOREIGN KEY (store_id) 
    REFERENCES stores (id) 
    ON UPDATE NO ACTION 
    ON DELETE SET NULL,

    CONSTRAINT FK_CATEGORIES_PRODUCTS 
    FOREIGN KEY (category_id) 
    REFERENCES categories (id) 
    ON UPDATE NO ACTION 
    ON DELETE SET NULL
);