CREATE TABLE order_items (
    id BIGINT(19) NOT NULL AUTO_INCREMENT,
    product_id BIGINT(19) NULL DEFAULT NULL,
    order_id BIGINT(19) NULL DEFAULT NULL,
    quantity INT(10) NULL DEFAULT NULL,
    PRIMARY KEY (id) USING BTREE,

    INDEX FK_PRODUCTS_OREDER_ITEMS (product_id) USING BTREE,
    INDEX FK_ORDERS_OREDER_ITEMS (order_id) USING BTREE,

    CONSTRAINT FK_PRODUCTS_OREDER_ITEMS 
    FOREIGN KEY (product_id) 
    REFERENCES products (id) 
    ON UPDATE CASCADE 
    ON DELETE CASCADE,

    CONSTRAINT FK_ORDERS_OREDER_ITEMS 
    FOREIGN KEY (order_id) 
    REFERENCES orders (id) 
    ON UPDATE NO ACTION 
    ON DELETE NO ACTION
);