CREATE TABLE requests (
    id BIGINT(19) NOT NULL AUTO_INCREMENT,
    user_id BIGINT(19) NULL DEFAULT NULL,
    verif_code VARCHAR(255) NULL DEFAULT NULL,
    timestamp BIGINT(19) NULL DEFAULT NULL,
    type TINYINT(1) NULL DEFAULT '0',

    PRIMARY KEY (id) USING BTREE,

    INDEX FK_USERS_REQUESTS (user_id) USING BTREE,

    CONSTRAINT FK_USERS_REQUESTS
        FOREIGN KEY (user_id)
        REFERENCES users (id)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);